name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has been marked a stale because it has been open for 14 days with no activity. If there is no further activity in the next 7 days this issue will be closed.'
          close-issue-message: 'This issue has been closed as there was no activity for 21 days. If this issue is still relevant, please request a reopen or create a new issue.'
          days-before-stale: 14
          days-before-close: 7
          any-of-labels: 'question,needs information,duplicate,incomplete,'
          exempt-issue-labels: 'bug'
