# Run unit tests against Python 2.7, 3.6+
# Based on OctoPrint's CI build file https://github.com/OctoPrint/OctoPrint/blob/master/.github/workflows/build.yml by @foosel

name: Test
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published, prereleased]
    
jobs:
  test-unit:
    name: 🧪 Unit tests
    strategy:
      matrix:
        python: ["2.7", "3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🏗 Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: 🏗 Set up test dependencies
        run: |
          pip install octoprint
          pip install -e .[develop]
      - name: 🚀 Run test suite
        run: |
          pytest
   
  test-flake8:
    name: 🧪 Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🏗 Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 🏗 Set up test dependencies
        run: |
          pip install -e .[develop]
      - name: 🚀 Run test suite
        run: |
          flake8 octoprint_ws281x_led_status tests setup.py

   test-install:
    name: 🧪 Installation tests
    needs: build
    strategy:
      matrix:
        python: ["2.7", "3.7", "3.8"]
        installable: ["wheel", "sdist"]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Download build result
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: 🏗 Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: 🚀 Install wheel
        if: matrix.installable == 'wheel'
        run: |
          pip install dist/OctoPrint-*-py2.py3-none-any.whl
      - name: 🚀 Install source tarball
        if: matrix.installable == 'sdist'
        run: |
          pip install dist/OctoPrint-*.tar.gz
